version: "3.6"

services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: postgres -c max_connections=300
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: claudiooak/spring-mds:1.0.3
    ports:
      - 8080:8080
    restart: on-failure:3
    depends_on:
      - db

  frontend:
    image: claudiooak/angular-mds:1.0.0
    ports:
      - "80:80"
    restart: on-failure:3
    depends_on:
      - db
      - backend

volumes:
  postgres_data:
    driver: local
    