version: "3.6"

services:

  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: postgres -c max_connections=300
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    command: sh -c "./mvnw clean compile spring-boot:run"
    ports:
      - 8080:8080
      - 5005:5005
    restart: on-failure:3
    user: nonroot
    volumes:
      - ./demo:/app


  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileDev
    command: sh -c "npm install && npm run start"
    ports:
      - "4200:4200"
    restart: on-failure:3
    volumes:
      - ./frontend:/frontend

volumes:
  postgres_data:
    driver: local
    